//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket_Sorgulari
    {
        public int AnketSorgu_Id { get; set; }
        public int Anket_Id { get; set; }
        public string Soru { get; set; }
        public string Cevap_A { get; set; }
        public string Cevap_B { get; set; }
        public string Cevap_C { get; set; }
        public string Kullanici_Cevap { get; set; }
        public int Mezun_Id { get; set; }
    
        public virtual Anketler Anketler { get; set; }
        public virtual Mezunlar Mezunlar { get; set; }
    }
}
