//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mezunlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mezunlar()
        {
            this.Anket_Sorgulari = new HashSet<Anket_Sorgulari>();
            this.Anketler = new HashSet<Anketler>();
            this.Mezun_Gonderileri = new HashSet<Mezun_Gonderileri>();
            this.Mezunlar_Sirketler = new HashSet<Mezunlar_Sirketler>();
        }
    
        public int Mezun_Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TC { get; set; }
        public string Tel_No { get; set; }
        public string Egitim_Bilgisi { get; set; }
        public string Yabanci_Dil { get; set; }
        public string Sertifika_Bilgisi { get; set; }
        public Nullable<int> Mezuniyet_Yili { get; set; }
        public int Sirket_Id { get; set; }
        public Nullable<bool> Calisma_Durumu { get; set; }
        public string Sifre { get; set; }
        public string Okul_Numarasi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anket_Sorgulari> Anket_Sorgulari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anketler> Anketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mezun_Gonderileri> Mezun_Gonderileri { get; set; }
        public virtual Sirketler Sirketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mezunlar_Sirketler> Mezunlar_Sirketler { get; set; }
    }
}
