//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mezunlar_Sirketler
    {
        public int MezunSirket_Id { get; set; }
        public int Mezun_Id { get; set; }
        public int Sirket_Id { get; set; }
        public System.DateTime Baslangıc_Tarihi { get; set; }
        public System.DateTime Bitis_Tarihi { get; set; }
    
        public virtual Mezunlar Mezunlar { get; set; }
        public virtual Sirketler Sirketler { get; set; }
    }
}
