//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MezunSistemiEntities : DbContext
    {
        public MezunSistemiEntities()
            : base("name=MezunSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anket_Sorgulari> Anket_Sorgulari { get; set; }
        public virtual DbSet<Anketler> Anketler { get; set; }
        public virtual DbSet<Arkadas> Arkadas { get; set; }
        public virtual DbSet<Ilanlar> Ilanlar { get; set; }
        public virtual DbSet<Mesajlar> Mesajlar { get; set; }
        public virtual DbSet<Mezun_Gonderileri> Mezun_Gonderileri { get; set; }
        public virtual DbSet<Mezunlar> Mezunlar { get; set; }
        public virtual DbSet<Mezunlar_Sirketler> Mezunlar_Sirketler { get; set; }
        public virtual DbSet<Sirketin_Departmanlari> Sirketin_Departmanlari { get; set; }
        public virtual DbSet<Sirketler> Sirketler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
